// Generated by infra/onboarding/release-manifest.ts. The release the hosted onboarding service
// installs; null until a release with published images is pinned.
import type { ReleaseManifest } from "./hosted-release.ts";

export const RELEASE_PIN: ReleaseManifest | null = null;
