// Pins a published release for the hosted onboarding service (infra/onboarding/spec.md §45). Run in
// a clean checkout of the release tag, after CI pushed its images; writes release-pin.ts in the
// repository given by --out (default: this checkout), which is then committed and deployed.
//
// Usage: node --experimental-strip-types infra/onboarding/release-manifest.ts <tag> \
//          --deployer ghcr.io/<org>/bye/deployer@sha256:… --scanner …@sha256:… \
//          --mime …@sha256:… --sigmirror …@sha256:… [--out <repo>]
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { parseArgs } from "node:util";
import { requiredConfig } from "../policies/check-config.ts";
import type { ReleaseManifest } from "./hosted-release.ts";
import { parseImageRef } from "./images.ts";
import { releaseMigrations, resolveRelease } from "./release.ts";

export const buildManifest = async (
  dir: string,
  tag: string,
  images: NonNullable<ReleaseManifest["ref"]["images"]>,
): Promise<ReleaseManifest> => {
  for (const ref of Object.values(images)) parseImageRef(ref);
  const resolved = resolveRelease(dir, tag);

  if (!resolved.ok) throw new Error(resolved.reason);

  return {
    format: "bye.onboarding-release.v1",
    ref: { ...resolved.release.ref, images },
    migrations: await releaseMigrations(dir),
    requiredConfig: requiredConfig(join(dir, "infra/resources")).map((c) => c.name),
    qualification: resolved.release.qualification ?? { newsletter: null },
  };
};

export const pinModule = (m: ReleaseManifest) =>
  `// Generated by infra/onboarding/release-manifest.ts. The release the hosted onboarding service
// installs; null until a release with published images is pinned.
import type { ReleaseManifest } from "./hosted-release.ts";

export const RELEASE_PIN: ReleaseManifest | null = ${JSON.stringify(m, null, 2)};
`;

if (import.meta.main) {
  const { values, positionals } = parseArgs({
    allowPositionals: true,
    options: {
      deployer: { type: "string" },
      scanner: { type: "string" },
      mime: { type: "string" },
      sigmirror: { type: "string" },
      out: { type: "string" },
    },
  });

  const [tag] = positionals;
  const { deployer, scanner, mime, sigmirror } = values;

  if (!tag || !deployer || !scanner || !mime || !sigmirror) {
    console.error(
      "usage: release-manifest.ts <tag> --deployer … --scanner … --mime … --sigmirror …",
    );
    process.exit(2);
  }

  const cwd = process.cwd();
  const manifest = await buildManifest(cwd, tag, { deployer, scanner, mime, sigmirror });
  const out = join(values.out ?? cwd, "infra/onboarding/release-pin.ts");
  writeFileSync(out, pinModule(manifest));
  console.log(`pinned ${tag} (${manifest.ref.commit.slice(0, 12)}) in ${out}`);
}
