// Bundles the deployer Worker (worker.ts) into one ES module and writes it as a string constant
// (worker.bundle.ts) for the hosted service to upload into installation accounts (remote.ts).
// `pnpm build:onboarding` regenerates it; a test fails when the committed bundle is stale.
//
// Usage: node --experimental-strip-types infra/onboarding/deployer/build.ts
import { writeFileSync } from "node:fs";
import { build } from "rolldown";

const dir = import.meta.dirname;

export const bundleDeployer = async (): Promise<string> => {
  const out = await build({
    input: `${dir}/worker.ts`,
    platform: "neutral",
    external: ["cloudflare:workers"],
    output: { format: "esm" },
    write: false,
    logLevel: "warn",
  });

  return out.output[0].code;
};

export const bundleModule = (code: string) =>
  `// Generated by infra/onboarding/deployer/build.ts from worker.ts. Do not edit.\nexport const DEPLOYER_WORKER_MODULE = ${JSON.stringify(code)};\n`;

if (import.meta.main) {
  writeFileSync(`${dir}/worker.bundle.ts`, bundleModule(await bundleDeployer()));
  console.log("built infra/onboarding/deployer/worker.bundle.ts");
}
