import type { Migration } from "../durable/sql.ts";

// MailboxDO application schema (§4.1). Message bodies and attachments live in R2; these rows
// hold metadata, organization state, and durable intentions only (§12 storage budget).

export const MAILBOX_MIGRATIONS: ReadonlyArray<Migration> = [
  {
    version: 1,
    name: "mailbox-core",
    statements: [
      `CREATE TABLE mailbox_settings (key TEXT PRIMARY KEY, value TEXT NOT NULL)`,
      `CREATE TABLE sender_policies (
        kind TEXT NOT NULL CHECK (kind IN ('address','domain')),
        subject TEXT NOT NULL,
        decision TEXT NOT NULL,
        destination TEXT NOT NULL,
        labels TEXT NOT NULL DEFAULT '[]',
        bundle INTEGER NOT NULL DEFAULT 0,
        notify INTEGER NOT NULL DEFAULT 0,
        updated_at INTEGER NOT NULL,
        PRIMARY KEY (kind, subject)
      )`,
      `CREATE TABLE policy_history (
        history_id TEXT PRIMARY KEY,
        kind TEXT NOT NULL,
        subject TEXT NOT NULL,
        prior TEXT,
        next TEXT,
        at INTEGER NOT NULL
      )`,
      `CREATE TABLE threads (
        thread_id TEXT PRIMARY KEY,
        subject TEXT NOT NULL,
        local_subject TEXT,
        sender TEXT NOT NULL,
        destination TEXT NOT NULL,
        disposition TEXT NOT NULL,
        disposition_at INTEGER NOT NULL,
        quarantined INTEGER NOT NULL DEFAULT 0,
        bundle_key TEXT,
        new_for_you INTEGER NOT NULL DEFAULT 0,
        revision INTEGER NOT NULL DEFAULT 0,
        seen_revision INTEGER NOT NULL DEFAULT 0,
        activity_seq INTEGER NOT NULL DEFAULT 0,
        last_activity_at INTEGER NOT NULL,
        message_count INTEGER NOT NULL DEFAULT 0,
        reply_later INTEGER NOT NULL DEFAULT 0,
        reply_later_at INTEGER,
        set_aside INTEGER NOT NULL DEFAULT 0,
        set_aside_at INTEGER,
        unfollowed INTEGER NOT NULL DEFAULT 0,
        bubble_tag TEXT NOT NULL DEFAULT 'None',
        bubble_at INTEGER,
        bubble_generation INTEGER NOT NULL DEFAULT 0,
        bubbled_at INTEGER,
        merged_into TEXT,
        created_at INTEGER NOT NULL
      )`,
      "CREATE INDEX threads_view ON threads (disposition, destination, last_activity_at)",
      `CREATE TABLE deliveries (
        delivery_id TEXT PRIMARY KEY,
        ingestion_id TEXT NOT NULL,
        recipient TEXT NOT NULL,
        thread_id TEXT NOT NULL,
        original_thread_id TEXT NOT NULL,
        direction TEXT NOT NULL CHECK (direction IN ('in','out')),
        message_key TEXT NOT NULL,
        message_id_header TEXT,
        in_reply_to TEXT NOT NULL DEFAULT '[]',
        refs TEXT NOT NULL DEFAULT '[]',
        from_address TEXT NOT NULL,
        from_name TEXT,
        to_json TEXT NOT NULL DEFAULT '[]',
        cc_json TEXT NOT NULL DEFAULT '[]',
        subject TEXT NOT NULL,
        date INTEGER NOT NULL,
        snippet TEXT NOT NULL DEFAULT '',
        list_id TEXT,
        automated INTEGER NOT NULL DEFAULT 0,
        raw_size INTEGER NOT NULL DEFAULT 0,
        thread_revision INTEGER NOT NULL,
        routing TEXT NOT NULL,
        received_at INTEGER NOT NULL,
        UNIQUE (ingestion_id, recipient)
      )`,
      "CREATE INDEX deliveries_thread ON deliveries (thread_id, date)",
      "CREATE INDEX deliveries_msgid ON deliveries (message_id_header)",
      "CREATE INDEX deliveries_from ON deliveries (from_address, date)",
      `CREATE TABLE attachments (
        delivery_id TEXT NOT NULL,
        part_id TEXT NOT NULL,
        thread_id TEXT NOT NULL,
        filename TEXT NOT NULL,
        content_type TEXT NOT NULL,
        size INTEGER NOT NULL,
        inline INTEGER NOT NULL DEFAULT 0,
        from_address TEXT NOT NULL,
        received_at INTEGER NOT NULL,
        PRIMARY KEY (delivery_id, part_id)
      )`,
      `CREATE TABLE labels (label_id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE, color TEXT)`,
      `CREATE TABLE thread_labels (thread_id TEXT NOT NULL, label_id TEXT NOT NULL, PRIMARY KEY (thread_id, label_id))`,
      `CREATE TABLE rules (
        rule_id TEXT PRIMARY KEY,
        position INTEGER NOT NULL,
        conditions TEXT NOT NULL,
        actions TEXT NOT NULL,
        enabled INTEGER NOT NULL DEFAULT 1
      )`,
      `CREATE TABLE merges (
        merge_id TEXT PRIMARY KEY,
        target_thread TEXT NOT NULL,
        source_threads TEXT NOT NULL,
        moved_deliveries TEXT NOT NULL,
        at INTEGER NOT NULL,
        undone_at INTEGER
      )`,
      `CREATE TABLE view_positions (view TEXT PRIMARY KEY, position TEXT, last_visit_at INTEGER NOT NULL DEFAULT 0, previous_visit_at INTEGER NOT NULL DEFAULT 0)`,
      `CREATE TABLE batches (batch_id TEXT PRIMARY KEY, thread_ids TEXT NOT NULL, created_at INTEGER NOT NULL)`,
      `CREATE TABLE workflow_boards (board_id TEXT PRIMARY KEY, name TEXT NOT NULL, enroll_address TEXT)`,
      `CREATE TABLE workflow_stages (stage_id TEXT PRIMARY KEY, board_id TEXT NOT NULL, name TEXT NOT NULL, position INTEGER NOT NULL)`,
      `CREATE TABLE workflow_cards (
        card_id TEXT PRIMARY KEY,
        board_id TEXT NOT NULL,
        stage_id TEXT NOT NULL,
        thread_id TEXT NOT NULL,
        position INTEGER NOT NULL,
        completed_at INTEGER,
        UNIQUE (board_id, thread_id)
      )`,
      `CREATE TABLE collections (collection_id TEXT PRIMARY KEY, name TEXT NOT NULL, created_at INTEGER NOT NULL)`,
      `CREATE TABLE collection_items (collection_id TEXT NOT NULL, thread_id TEXT NOT NULL, added_at INTEGER NOT NULL, PRIMARY KEY (collection_id, thread_id))`,
      `CREATE TABLE notes (
        note_id TEXT PRIMARY KEY,
        kind TEXT NOT NULL CHECK (kind IN ('thread','sticky','cover')),
        thread_id TEXT,
        body TEXT NOT NULL,
        file_keys TEXT NOT NULL DEFAULT '[]',
        revision INTEGER NOT NULL,
        updated_at INTEGER NOT NULL
      )`,
      `CREATE TABLE clips (clip_id TEXT PRIMARY KEY, thread_id TEXT NOT NULL, delivery_id TEXT NOT NULL, text TEXT NOT NULL, created_at INTEGER NOT NULL)`,
      `CREATE TABLE contacts (contact_id TEXT PRIMARY KEY, name TEXT NOT NULL, emails TEXT NOT NULL, notes TEXT NOT NULL DEFAULT '', updated_at INTEGER NOT NULL)`,
      `CREATE TABLE contact_groups (group_id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE)`,
      `CREATE TABLE contact_group_members (group_id TEXT NOT NULL, contact_id TEXT NOT NULL, PRIMARY KEY (group_id, contact_id))`,
      `CREATE TABLE recent_recipients (address TEXT PRIMARY KEY, name TEXT, last_used_at INTEGER NOT NULL, uses INTEGER NOT NULL)`,
      `CREATE TABLE identities (
        identity_id TEXT PRIMARY KEY,
        address TEXT NOT NULL UNIQUE,
        name TEXT,
        kind TEXT NOT NULL CHECK (kind IN ('hosted','external')),
        verified INTEGER NOT NULL DEFAULT 0,
        is_default INTEGER NOT NULL DEFAULT 0,
        signature TEXT NOT NULL DEFAULT ''
      )`,
      `CREATE TABLE drafts (
        draft_id TEXT PRIMARY KEY,
        thread_id TEXT,
        identity_id TEXT,
        revision INTEGER NOT NULL,
        content TEXT NOT NULL,
        state TEXT NOT NULL,
        updated_at INTEGER NOT NULL
      )`,
      `CREATE TABLE draft_revisions (draft_id TEXT NOT NULL, revision INTEGER NOT NULL, content TEXT NOT NULL, PRIMARY KEY (draft_id, revision))`,
      `CREATE TABLE send_jobs (
        send_job_id TEXT PRIMARY KEY,
        draft_id TEXT NOT NULL,
        draft_revision INTEGER NOT NULL,
        split_key TEXT NOT NULL DEFAULT '',
        state TEXT NOT NULL,
        due_at INTEGER NOT NULL,
        identity_id TEXT NOT NULL,
        from_address TEXT NOT NULL,
        recipients TEXT NOT NULL,
        thread_id TEXT,
        traffic_class TEXT NOT NULL,
        content_key TEXT NOT NULL,
        bytes INTEGER NOT NULL DEFAULT 0,
        attempts INTEGER NOT NULL DEFAULT 0,
        max_attempts INTEGER NOT NULL DEFAULT 5,
        provider_id TEXT,
        wire_message_id TEXT,
        failure TEXT,
        after_send TEXT NOT NULL DEFAULT '{"_tag":"None"}',
        created_at INTEGER NOT NULL,
        updated_at INTEGER NOT NULL
      )`,
      "CREATE UNIQUE INDEX send_jobs_intent ON send_jobs (draft_id, draft_revision, split_key) WHERE state <> 'cancelled'",
      "CREATE INDEX send_jobs_state ON send_jobs (state, updated_at)",
      `CREATE TABLE send_recipients (
        send_job_id TEXT NOT NULL,
        address TEXT NOT NULL,
        outcome TEXT NOT NULL,
        detail TEXT,
        updated_at INTEGER NOT NULL,
        PRIMARY KEY (send_job_id, address)
      )`,
      `CREATE TABLE uploads (
        upload_id TEXT PRIMARY KEY,
        filename TEXT NOT NULL,
        content_type TEXT NOT NULL,
        declared_size INTEGER NOT NULL,
        actual_size INTEGER,
        state TEXT NOT NULL,
        scan_status TEXT NOT NULL DEFAULT 'pending',
        parts TEXT NOT NULL DEFAULT '[]',
        blob_key TEXT NOT NULL,
        created_at INTEGER NOT NULL
      )`,
      `CREATE TABLE file_links (
        link_id TEXT PRIMARY KEY,
        secret TEXT NOT NULL,
        upload_id TEXT NOT NULL,
        expires_at INTEGER,
        revoked_at INTEGER,
        created_at INTEGER NOT NULL
      )`,
      `CREATE TABLE away_sent (sender TEXT PRIMARY KEY, last_sent_at INTEGER NOT NULL)`,
      `CREATE TABLE forwarding_destinations (address TEXT PRIMARY KEY, token TEXT NOT NULL, verified INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL)`,
      `CREATE TABLE forwarding_rules (rule_id TEXT PRIMARY KEY, match_sender TEXT, destination TEXT NOT NULL, keep_copy INTEGER NOT NULL DEFAULT 1)`,
      `CREATE TABLE notify_opt_in (kind TEXT NOT NULL CHECK (kind IN ('contact','domain','thread')), subject TEXT NOT NULL, PRIMARY KEY (kind, subject))`,
      `CREATE TABLE transfers (transfer_id TEXT PRIMARY KEY, direction TEXT NOT NULL, peer_mailbox TEXT NOT NULL, delivery_id TEXT NOT NULL, mode TEXT NOT NULL, at INTEGER NOT NULL)`,
    ],
  },
  {
    // Expand-only (§15.9). Rows committed before scanning existed are `legacy`: not rescanned
    // automatically, treated like `clean` for access, and eligible for an operator backfill.
    version: 2,
    name: "delivery-scan-status",
    statements: [
      "ALTER TABLE deliveries ADD COLUMN scan_status TEXT NOT NULL DEFAULT 'legacy'",
      "ALTER TABLE deliveries ADD COLUMN scan_signature TEXT",
      "ALTER TABLE deliveries ADD COLUMN scan_attempts INTEGER NOT NULL DEFAULT 0",
      "CREATE INDEX deliveries_scan ON deliveries (scan_status, received_at)",
    ],
  },
  {
    // Expand-only (§15.9): search shard catalog and placement (§8 rollover), pending index
    // events (indexing watermark), R2 multipart upload IDs (E20), external send-as challenges (E19).
    version: 3,
    name: "search-catalog-uploads-identity-challenge",
    statements: [
      `CREATE TABLE search_shards (
        name TEXT PRIMARY KEY,
        from_date INTEGER NOT NULL,
        created_at INTEGER NOT NULL,
        sealed_at INTEGER,
        stored_bytes INTEGER NOT NULL DEFAULT 0
      )`,
      `CREATE TABLE search_placement (doc_key TEXT PRIMARY KEY, shard TEXT NOT NULL)`,
      `CREATE TABLE index_pending (doc_key TEXT PRIMARY KEY, emitted_seq INTEGER NOT NULL)`,
      "ALTER TABLE uploads ADD COLUMN r2_upload_id TEXT",
      "ALTER TABLE identities ADD COLUMN challenge_token TEXT",
      "ALTER TABLE identities ADD COLUMN challenge_sent_at INTEGER",
    ],
  },
  {
    // Table rebuild (the sanctioned SQLite way to relax a constraint): forwarding jobs reuse the
    // original bytes and send as no identity of ours, so `identity_id` becomes nullable and the
    // old `'forwarding'` sentinel is migrated to NULL.
    version: 4,
    name: "send-jobs-nullable-identity",
    statements: [
      `CREATE TABLE send_jobs_v4 (
        send_job_id TEXT PRIMARY KEY,
        draft_id TEXT NOT NULL,
        draft_revision INTEGER NOT NULL,
        split_key TEXT NOT NULL DEFAULT '',
        state TEXT NOT NULL,
        due_at INTEGER NOT NULL,
        identity_id TEXT,
        from_address TEXT NOT NULL,
        recipients TEXT NOT NULL,
        thread_id TEXT,
        traffic_class TEXT NOT NULL,
        content_key TEXT NOT NULL,
        bytes INTEGER NOT NULL DEFAULT 0,
        attempts INTEGER NOT NULL DEFAULT 0,
        max_attempts INTEGER NOT NULL DEFAULT 5,
        provider_id TEXT,
        wire_message_id TEXT,
        failure TEXT,
        after_send TEXT NOT NULL DEFAULT '{"_tag":"None"}',
        created_at INTEGER NOT NULL,
        updated_at INTEGER NOT NULL
      )`,
      `INSERT INTO send_jobs_v4 (send_job_id, draft_id, draft_revision, split_key, state, due_at, identity_id, from_address, recipients,
         thread_id, traffic_class, content_key, bytes, attempts, max_attempts, provider_id, wire_message_id, failure, after_send, created_at, updated_at)
       SELECT send_job_id, draft_id, draft_revision, split_key, state, due_at, CASE WHEN identity_id = 'forwarding' THEN NULL ELSE identity_id END,
         from_address, recipients, thread_id, traffic_class, content_key, bytes, attempts, max_attempts, provider_id, wire_message_id, failure,
         after_send, created_at, updated_at FROM send_jobs`,
      "DROP TABLE send_jobs",
      "ALTER TABLE send_jobs_v4 RENAME TO send_jobs",
      "CREATE UNIQUE INDEX send_jobs_intent ON send_jobs (draft_id, draft_revision, split_key) WHERE state <> 'cancelled'",
      "CREATE INDEX send_jobs_state ON send_jobs (state, updated_at)",
      "CREATE INDEX send_jobs_draft ON send_jobs (draft_id)",
    ],
  },
  {
    // Conditional Bubble Up (E09). Existing scheduled bubbles keep their unconditional meaning.
    version: 5,
    name: "bubble-condition",
    statements: ["ALTER TABLE threads ADD COLUMN bubble_condition TEXT NOT NULL DEFAULT 'always'"],
  },
];
